year: '2019'                       # Year of the flight
month: '10'                         # Month of the flight
day: '08'                           # Day of the flight

simulation_parameters:
  debug: true                      # Debug mode
  timestep: 0.1                       # Timestep in seconds
  n_tether_elements: 10                # Number of tether elements
  doIEKF: true                        # Use iterated extended Kalman filter
  epsilon: 1e-6                       # Tolerance for the IEKF
  max_iterations: 200                 # Maximum number of iterations for the IEKF
  log_profile: false                   # Model wind speed as logarithmic with height
  enforce_z_wind: false               # Enforce the vertical wind speed to be zero (change to )
  model_yaw: false                   # Model the yaw angle in the state vector

  measurements:
    kite_position: true                   # Kite position measurement
    kite_velocity: true                   # Kite velocity measurement
    kite_acceleration: true                   # Kite acceleration measurement
    tether_force: true               # Tether force measurement
    tether_length: true              # Tether length measurement
    tether_elevation: false           # Tether elevation angle measurement
    tether_azimuth: false             # Tether azimuth angle measurement
    kcu_position: false                    # KCU position measurement
    kcu_velocity: false                    # KCU velocity measurement
    kcu_acceleration: false                    # KCU acceleration measurement
    kite_apparent_windspeed: true         # Apparent wind speed measurement
    bridle_angle_of_attack: false            # Angle of attack measurement
    bridle_angle_of_sideslip: false             # Sideslip angle measurement
    kite_yaw_angle: false                  # Yaw angle measurement

kite:
  model_name: 'v3'                # Kite model
  mass: 15                        # Mass of the kite in kg
  area: 19.75                    # Area of the kite in m^2
  span: 10                      # Span of the kite in m
  sensor_ids:                     # Sensor IDs of the kite
    - 0
    - 1
kcu:
  length: 1                     # Length of the KCU in m
  diameter: 0.48                      # Width of the KCU in m
  mass: 27.6                       # Mass of the KCU in kg
  distance_kcu_kite: 11.5        # Distance from the KCU cg to the kite cg in m
  total_length_bridle_lines: 96  # Total length of the bridle lines in m
  diameter_bridle_lines: 0.0025    # Diameter of the bridle lines in m
tether:
  material_name: 'Dyneema-SK78'   # Material name of the tether
  diameter: 0.01               # Diameter of the tether in m
  n_elements: 5                # Number of tether elements


tuning_parameters:
  meas_stdv:
    x: 2.5
    v: 1
    tether_length: 1
    tether_elevation: 0.2
    tether_azimuth: 0.2
    least_squares: 1e-5
    yaw: 0.15  # 10 degrees in radians
    z_wind: 2
    va: 0.5
    aoa: 4
  model_stdv:
    x: 2.5
    v: 1
    uf: 0.002
    wdir: 0.00349  # 0.2 degrees in radians
    vw: 0.1
    vwz: 0.01
    CL: 0.01
    CD: 0.003
    CS: 0.01
    tether_elevation: 0.3
    tether_azimuth: 0.3
    tether_length: 0.1
    yaw: 0.0873

postprocess:
  # Posprocessing settings
  remove_IMU_offsets: true  # Remove IMU offsets, only for soft wing with KCU
  correct_IMU_deformation: true # Correct IMU deformation, only for soft wing with KCU
  remove_vane_offsets: true # Remove vane offsets, only for soft wing with KCU
  estimate_kite_angle: true # Estimate kite angle, only for soft wing with KCU